"""Self-contained HTML report + machine-readable report.json."""

from __future__ import annotations

import html
import json
import os
import time
from pathlib import Path

import numpy as np

from . import __version__, plots
from .agent import AnalysisResult
from .findings import number_matches
from .session import Session

UI = {
    "zh": {
        "title": "试验数据分析报告",
        "file": "数据文件",
        "agent": "分析方式",
        "generated": "生成时间",
        "findings": "结论",
        "critical": "关键",
        "warning": "警告",
        "info": "信息",
        "verified": "已验证结论",
        "numbers": "数字可溯源",
        "evidence": "证据条目",
        "summary": "摘要",
        "overview": "全程概览",
        "overview_note": "阴影为试验阶段，编号对应下方结论（概览图仅用于导航，不作为证据）。",
        "evidence_h": "证据账本",
        "evidence_note": "每条证据都是一次确定性工具调用，记录了参数、数据哈希与工具版本，可用下方代码或 "
                         "<code>groundline reproduce report.json</code> 复现。",
        "params": "参数",
        "result": "结果（JSON）",
        "reproduce": "复现",
        "status_verified": "已验证",
        "status_partial": "部分未溯源",
        "status_unsupported": "无证据",
        "ungrounded": "以下数字未在引用证据中找到",
        "semantic": "数字有出处，但与句中含义不符",
        "problems": "问题",
        "cites": "引用证据",
        "none": "未发现需要报告的问题。",
        "tool_version": "工具版本",
        "data_hash": "数据 SHA-256",
        "elapsed": "耗时",
        "footer": "由 groundline {v} 生成。报告中的每个数字都应能在所引用的证据中找到；未能溯源的数字会以红色波浪线标出。",
    },
    "en": {
        "title": "Test Data Analysis Report",
        "file": "Data file",
        "agent": "Analysis",
        "generated": "Generated",
        "findings": "Findings",
        "critical": "Critical",
        "warning": "Warning",
        "info": "Info",
        "verified": "Verified claims",
        "numbers": "Numbers traceable",
        "evidence": "Evidence entries",
        "summary": "Summary",
        "overview": "Overview",
        "overview_note": "Shaded bands are test phases; numbers refer to the findings below (navigation only, not evidence).",
        "evidence_h": "Evidence ledger",
        "evidence_note": "Each entry is a deterministic tool call with its parameters, data hash and tool version. Re-run it "
                         "with the snippet or <code>groundline reproduce report.json</code>.",
        "params": "Parameters",
        "result": "Result (JSON)",
        "reproduce": "Reproduce",
        "status_verified": "Verified",
        "status_partial": "Partly ungrounded",
        "status_unsupported": "No evidence",
        "ungrounded": "Numbers not found in the cited evidence",
        "semantic": "Numbers found, but not with the meaning the sentence gives them",
        "problems": "Problems",
        "cites": "Evidence",
        "none": "Nothing to report.",
        "tool_version": "Tool version",
        "data_hash": "Data SHA-256",
        "elapsed": "Elapsed",
        "footer": "Generated by groundline {v}. Every number in this report should appear in the evidence it cites; "
                  "numbers that cannot be traced are underlined in red.",
    },
}

SEV_ICON = {"critical": "▲", "warning": "●", "info": "ℹ"}

CSS = """
:root{--bg:#f6f5f2;--surface:#fcfcfb;--ink:#0b0b0b;--ink2:#52514e;--ink3:#7a7974;--line:#e4e3df;
--accent:#2a78d6;--crit:#d03b3b;--warn:#b37d00;--good:#0a7f0a;--chip:#eef3fb;--code:#f1f0ec}
@media (prefers-color-scheme: dark){:root:not([data-theme="light"]){--bg:#121211;--surface:#1a1a19;--ink:#fff;
--ink2:#c3c2b7;--ink3:#8f8e86;--line:#2e2e2b;--accent:#3987e5;--crit:#e66767;--warn:#fab219;--good:#3fbf3f;
--chip:#1f2a3a;--code:#222220}}
:root[data-theme="dark"]{--bg:#121211;--surface:#1a1a19;--ink:#fff;--ink2:#c3c2b7;--ink3:#8f8e86;--line:#2e2e2b;
--accent:#3987e5;--crit:#e66767;--warn:#fab219;--good:#3fbf3f;--chip:#1f2a3a;--code:#222220}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",
"PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif}
main{max-width:1040px;margin:0 auto;padding:32px 16px 64px}
h1{font-size:26px;margin:0 0 4px;letter-spacing:-.01em}
h2{font-size:18px;margin:40px 0 12px}
.meta{color:var(--ink2);font-size:13px;display:flex;flex-wrap:wrap;gap:4px 20px}
.meta code{font-size:12px}
.kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:24px 0}
.kpi{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:12px 14px}
.kpi .v{font-size:24px;font-weight:650;font-variant-numeric:tabular-nums}
.kpi .l{color:var(--ink2);font-size:12px}
.kpi .sub{font-size:12px;color:var(--ink3)}
.summary{background:var(--surface);border:1px solid var(--line);border-left:3px solid var(--accent);
border-radius:10px;padding:14px 16px}
.fig{background:#fcfcfb;border-radius:8px;padding:6px;border:1px solid var(--line)}
.fig img{width:100%;height:auto;display:block}
.note{color:var(--ink3);font-size:12px;margin:6px 2px}
.finding{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:14px 16px;margin:10px 0;
display:grid;grid-template-columns:34px 1fr;gap:0 12px}
.num{width:28px;height:28px;border-radius:50%;background:var(--code);display:grid;place-items:center;
font-weight:650;font-size:13px;color:var(--ink2)}
.finding h3{margin:2px 0 6px;font-size:16px}
.tags{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:8px;font-size:12px}
.tag{padding:1px 8px;border-radius:999px;background:var(--code);color:var(--ink2)}
.sev-critical{color:var(--crit);font-weight:600}
.sev-warning{color:var(--warn);font-weight:600}
.sev-info{color:var(--ink2);font-weight:600}
.st-verified{color:var(--good)}
.st-partial{color:var(--warn)}
.st-unsupported{color:var(--crit)}
.stmt{margin:0 0 8px}
.g{border-bottom:1px dotted var(--ink3);cursor:help}
.ng{text-decoration:underline wavy var(--crit);text-underline-offset:3px}
.chips a{display:inline-block;margin:2px 4px 0 0;padding:1px 8px;border-radius:6px;background:var(--chip);
color:var(--accent);text-decoration:none;font:600 12px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace}
.chips a:hover{text-decoration:underline}
.warnbox{margin-top:8px;font-size:13px;color:var(--crit)}
.ev{background:var(--surface);border:1px solid var(--line);border-radius:10px;margin:12px 0;scroll-margin-top:12px}
.ev>summary{cursor:pointer;padding:10px 14px;display:flex;gap:10px;align-items:baseline;flex-wrap:wrap;list-style:none}
.ev>summary::-webkit-details-marker{display:none}
.ev>summary .id{font:700 13px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--accent)}
.ev>summary .tool{font-weight:600}
.ev>summary .p{color:var(--ink3);font:12px ui-monospace,SFMono-Regular,Menlo,monospace;overflow-wrap:anywhere}
.ev:target{outline:2px solid var(--accent)}
.evb{padding:0 14px 14px}
pre{background:var(--code);border-radius:8px;padding:10px 12px;overflow:auto;font-size:12px;line-height:1.5;margin:6px 0}
code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
.kv{font-size:12px;color:var(--ink3);display:flex;flex-wrap:wrap;gap:4px 16px;margin:6px 0}
details.inner>summary{cursor:pointer;font-size:13px;color:var(--ink2);margin-top:8px}
footer{margin-top:48px;color:var(--ink3);font-size:12px}
@media (max-width:600px){.finding{grid-template-columns:1fr}.num{display:none}h1{font-size:22px}}
"""


def _esc(x) -> str:
    return html.escape(str(x))


def _highlight(text: str, numbers: list[dict]) -> str:
    """Wrap each number in the statement with its grounding status."""
    out, pos, k = [], 0, 0
    for m in number_matches(text):
        out.append(_esc(text[pos : m.start()]))
        n = numbers[k] if k < len(numbers) else None
        k += 1
        tok = _esc(m.group(0))
        if n and n["grounded"] and n.get("consistent", True):
            mv = n["matched"]
            sc = "" if mv["scale"] == 1 else f" × {mv['scale']:g}"
            src = f" ({mv['field']})" if mv.get("field") else ""
            out.append(f'<span class="g" title="= {_esc(str(mv["value"]))}{sc}{_esc(src)}">{tok}</span>')
        elif n and n["grounded"]:
            out.append(f'<span class="ng" title="{_esc(n.get("semantic_problem") or "")}">{tok}</span>')
        elif n:
            out.append(f'<span class="ng" title="not found in cited evidence">{tok}</span>')
        else:
            out.append(tok)
        pos = m.end()
    out.append(_esc(text[pos:]))
    return "".join(out)


def _overview_png(s: Session, result: AnalysisResult) -> str:
    kinds = ["pressure", "temperature", "flow", "vibration"]
    groups = [(k, s.channels_of_kind(k)) for k in kinds if s.channels_of_kind(k)]
    if not groups:
        groups = [("other", s.channels[:4])]
    fig, axes = plots.new_fig(len(groups), height=1.7)
    t = s.time
    step = max(len(t) // 6000, 1)
    phases = s.phases()
    for ax, (kind, chans) in zip(axes, groups):
        plots.shade_phases(ax, phases)
        for i, ch in enumerate(chans[:4]):
            ax.plot(t[::step], s.data[ch].to_numpy()[::step], lw=0.8, color=plots.SERIES[i], label=ch)
        unit = s.channel_info(chans[0]).get("unit", "")
        ax.set_ylabel(f"{kind} [{unit}]", fontsize=8)
        if len(chans) > 1:
            ax.legend(loc="upper right", ncol=min(len(chans), 4))
    for i, f in enumerate(result.findings, 1):
        if f.t_start is None or f.category == "observation":
            continue
        ax = next((a for a, (_, ch) in zip(axes, groups) if f.channel in ch), axes[0])
        t1 = f.t_end if f.t_end is not None else f.t_start
        col = plots.CRITICAL if f.severity == "critical" else plots.WARNING
        ax.axvspan(f.t_start, max(t1, f.t_start + 0.02), color=col, alpha=0.18 if f.severity == "critical" else 0.10, lw=0)
        ax.annotate(str(i), (f.t_start, 1.0), xycoords=("data", "axes fraction"), ha="left", va="top",
                    fontsize=8, fontweight="bold", color=plots.INK,
                    bbox=dict(boxstyle="circle,pad=0.2", fc="white", ec=col, lw=1))
    axes[-1].set_xlabel("time [s]")
    return plots.to_base64(fig)


def build_report(s: Session, result: AnalysisResult, lang: str = "zh") -> str:
    L = UI.get(lang, UI["zh"])
    F = result.findings
    ver = result.verification
    run_path = s.paths.get("run") or "(in-memory)"
    agent = result.agent
    agent_s = agent.get("type", "")
    if agent_s == "llm":
        agent_s = f"LLM · {agent.get('backend')} · {agent.get('model')}"
    elif agent_s == "rule":
        agent_s = "rule-based playbook"
    sev = {k: sum(f.severity == k for f in F) for k in ("critical", "warning", "info")}
    parts = [f"<!doctype html><html lang='{'zh-CN' if lang == 'zh' else 'en'}'><head><meta charset='utf-8'>",
             "<meta name='viewport' content='width=device-width,initial-scale=1'>",
             f"<title>{_esc(L['title'])} · {_esc(s.meta.get('test_id', ''))}</title><style>{CSS}</style></head><body><main>"]
    parts.append(f"<h1>{_esc(L['title'])} · {_esc(s.meta.get('test_id', ''))}</h1>")
    parts.append(
        f"<div class='meta'><span>{L['file']}: <code>{_esc(os.path.basename(run_path))}</code></span>"
        f"<span>SHA-256 <code>{s.data_sha256[:16]}…</code></span>"
        f"<span>{L['agent']}: {_esc(agent_s)}</span>"
        f"<span>{L['generated']}: {time.strftime('%Y-%m-%d %H:%M')}</span></div>"
    )
    parts.append("<div class='kpis'>")
    parts.append(f"<div class='kpi'><div class='v'>{len(F)}</div><div class='l'>{L['findings']}</div>"
                 f"<div class='sub'><span class='sev-critical'>{SEV_ICON['critical']} {sev['critical']}</span> · "
                 f"<span class='sev-warning'>{SEV_ICON['warning']} {sev['warning']}</span> · "
                 f"<span class='sev-info'>{SEV_ICON['info']} {sev['info']}</span></div></div>")
    parts.append(f"<div class='kpi'><div class='v'>{ver.get('verified', 0)}/{len(F)}</div>"
                 f"<div class='l'>{L['verified']}</div></div>")
    parts.append(f"<div class='kpi'><div class='v'>{ver.get('numbers_grounded', 0)}/{ver.get('numbers_total', 0)}</div>"
                 f"<div class='l'>{L['numbers']}</div></div>")
    parts.append(f"<div class='kpi'><div class='v'>{len(s.ledger)}</div><div class='l'>{L['evidence']}</div>"
                 f"<div class='sub'>{result.elapsed_s:.1f} s</div></div>")
    parts.append("</div>")
    parts.append(f"<div class='summary'><strong>{L['summary']}</strong> — {_esc(result.summary)}</div>")

    parts.append(f"<h2>{L['overview']}</h2><div class='fig'><img alt='overview' "
                 f"src='data:image/png;base64,{_overview_png(s, result)}'></div><p class='note'>{L['overview_note']}</p>")

    parts.append(f"<h2>{L['findings']}</h2>")
    if not F:
        parts.append(f"<p>{L['none']}</p>")
    for i, f in enumerate(F, 1):
        v = f.verification or {}
        st = v.get("status", "unsupported")
        tw = ""
        if f.t_start is not None:
            tw = f"{f.t_start:.3f}" + (f"–{f.t_end:.3f} s" if f.t_end is not None else " s")
        tags = [f"<span class='sev-{_esc(f.severity)}'>{SEV_ICON.get(f.severity, '')} {_esc(L.get(f.severity, f.severity))}</span>",
                f"<span class='tag'>{_esc(f.category)}</span>"]
        if f.channel:
            tags.append(f"<span class='tag'>{_esc(f.channel)}</span>")
        if tw:
            tags.append(f"<span class='tag'>{tw}</span>")
        tags.append(f"<span class='st-{st}'>{'✓' if st == 'verified' else '!'} {L['status_' + st]}</span>")
        nums = v.get("numbers", [])
        n_title = len(number_matches(f.title))
        title_html = _highlight(f.title, nums[:n_title])
        stmt_html = _highlight(f.statement, nums[n_title:])
        chips = "".join(f"<a href='#{_esc(e)}'>{_esc(e)}</a>" for e in f.evidence)
        warn = ""
        if v.get("ungrounded_numbers") or v.get("semantic_problems") or v.get("problems"):
            items = []
            if v.get("ungrounded_numbers"):
                items.append(f"{L['ungrounded']}: {_esc(', '.join(v['ungrounded_numbers']))}")
            if v.get("semantic_problems"):
                items.append(f"{L['semantic']}: {_esc('; '.join(v['semantic_problems']))}")
            if v.get("problems"):
                items.append(f"{L['problems']}: {_esc('; '.join(v['problems']))}")
            warn = "<div class='warnbox'>" + "<br>".join(items) + "</div>"
        parts.append(
            f"<div class='finding' id='F{i}'><div class='num'>{i}</div><div><div class='tags'>{''.join(tags)}</div>"
            f"<h3>{title_html}</h3><p class='stmt'>{stmt_html}</p>"
            f"<div class='chips'><span class='note'>{L['cites']}:</span> {chips}</div>{warn}</div></div>"
        )

    parts.append(f"<h2>{L['evidence_h']}</h2><p class='note'>{L['evidence_note']}</p>")
    cited = {e for f in F for e in f.evidence}
    for ev in s.ledger:
        p = ", ".join(f"{k}={v}" for k, v in ev.params.items()) or "—"
        code = ev.reproduce_code(s.paths.get("run") or "run.csv", s.paths.get("reference"), s.paths.get("limits"))
        fig = f"<div class='fig'><img alt='{_esc(ev.id)}' src='data:image/png;base64,{ev.figure_png}'></div>" \
            if ev.figure_png else ""
        parts.append(
            f"<details class='ev' id='{_esc(ev.id)}' {'open' if ev.id in cited and ev.figure_png else ''}>"
            f"<summary><span class='id'>{_esc(ev.id)}</span><span class='tool'>{_esc(ev.tool)}</span>"
            f"<span class='p'>{_esc(p)}</span></summary><div class='evb'>{fig}"
            f"<div class='kv'><span>{L['tool_version']}: <code>{_esc(ev.tool_version)}</code></span>"
            f"<span>{L['data_hash']}: <code>{ev.data_sha256[:16]}…</code></span>"
            f"<span>{L['elapsed']}: {ev.elapsed_ms} ms</span></div>"
            f"<details class='inner'><summary>{L['result']}</summary><pre>{_esc(json.dumps(ev.result, indent=2, ensure_ascii=False))}</pre></details>"
            f"<details class='inner'><summary>{L['reproduce']}</summary><pre>{_esc(code)}</pre></details>"
            f"</div></details>"
        )
    parts.append(f"<footer>{_esc(L['footer'].format(v=__version__))}</footer></main></body></html>")
    return "".join(parts)


def report_json(s: Session, result: AnalysisResult) -> dict:
    return {
        "groundline_version": __version__,
        "test_id": s.meta.get("test_id"),
        "paths": s.paths,
        "data_sha256": s.data_sha256,
        "agent": result.agent,
        "summary": result.summary,
        "verification": result.verification,
        "findings": [f.to_dict() for f in result.findings],
        "evidence": s.ledger_json(),
        "elapsed_s": result.elapsed_s,
    }


def write_report(s: Session, result: AnalysisResult, out_html: str | Path, lang: str = "zh") -> dict[str, Path]:
    out_html = Path(out_html)
    out_html.parent.mkdir(parents=True, exist_ok=True)
    out_html.write_text(build_report(s, result, lang), encoding="utf-8")
    js = out_html.with_suffix(".json")
    data = report_json(s, result)
    # store paths relative to the report as well so the bundle can be moved together
    rel = {}
    for k, v in (s.paths or {}).items():
        if v:
            try:
                rel[k] = os.path.relpath(Path(v).resolve(), out_html.parent.resolve())
            except ValueError:
                rel[k] = v
    data["paths_relative"] = rel
    js.write_text(json.dumps(data, indent=2, ensure_ascii=False, default=lambda o: float(o) if isinstance(o, np.floating) else str(o)),
                  encoding="utf-8")
    return {"html": out_html, "json": js}
